--CREATE DATABASE BIRDS

--ALTER DATABASE BIRDS RENAME TO CATS

--DROP DATABASE IF EXISTS CATS

CREATE TABLE OVOCHIFRUKTY (
    id SERIAL PRIMARY KEY,
    nazva TEXT NOT NULL,
    typ TEXT CHECK (typ IN ('Овоч', 'Фрукт')) NOT NULL,
    kolir TEXT NOT NULL,
    kalorijnist INTEGER NOT NULL,
    opis TEXT
);

SELECT * FROM OVOCHIFRUKTY

SELECT * FROM OVOCHIFRUKTY WHERE typ = 'Овоч';

SELECT * FROM OVOCHIFRUKTY WHERE typ = 'Фрукт';

SELECT nazva FROM OVOCHIFRUKTY;

SELECT DISTINCT kolir FROM OVOCHIFRUKTY;

SELECT * FROM OVOCHIFRUKTY WHERE typ = 'Фрукт' AND kolir = 'жовтий';

SELECT * FROM OVOCHIFRUKTY WHERE typ = 'Овоч' AND kolir = 'зелений';





